#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"

if [[ -f "${ENV_FILE}" ]]; then
  echo "ivory-cloud-setup: keeping existing ${ENV_FILE}"
  exit 0
fi

cp "${ROOT_DIR}/.env.example" "${ENV_FILE}"

cat >> "${ENV_FILE}" <<'EOF'

# Cursor Cloud / Compose profile (generated by scripts/ivory-cloud-setup.sh)
IVORY_S3_BUCKET=ivory-tower
IVORY_S3_ENDPOINT=http://localhost:9000
IVORY_S3_ACCESS_KEY_ID=ivory
IVORY_S3_SECRET_ACCESS_KEY=ivory-development-only
IVORY_S3_FORCE_PATH_STYLE=true
EOF

echo "ivory-cloud-setup: wrote ${ENV_FILE} with local Compose defaults"
